apiVersion: v1
kind: Service
metadata:
  name: flow-reader
  namespace: default
  labels:
    app: flow-reader
spec:
  type: LoadBalancer
  ports:
  - port: 3005
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: flow-reader
